name: Build & Test
on: [push, pull_request]
jobs:
  build-ubuntu:
    name: libSMCE - Linux (${{ matrix.compiler.name }} & Boost ${{ matrix.boost }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: GCC 10
            c: gcc-10
            cxx: g++-10
          - name: Clang/LLVM 10
            c: clang-10
            cxx: clang++-10
        boost: [1.74.0, 1.75.0]
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: boost_root
          key: ${{ runner.os }}-boost-${{ matrix.boost }}
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          export BOOST_ARK_BASENAME=$(echo ${{ matrix.boost }} | sed "s/^/boost_/;s/\./_/g")
          wget -qOboost_src.tgz https://dl.bintray.com/boostorg/release/${{ matrix.boost }}/source/$BOOST_ARK_BASENAME.tar.gz
          tar -xzf ./boost_src.tgz
          mkdir boost_root
          cd $BOOST_ARK_BASENAME
          ./bootstrap.sh --prefix=../boost_root/
          ./b2 link=static install
          cd ../
      - name: Check deps
        run: |
          sudo apt install ninja-build
          ninja --version # technically not a dependency, but used to speedup builds
          cmake --version
          brew install arduino-cli
          arduino-cli version
          arduino-cli core install arduino:avr
      - name: CMake configure
        run: |
          export BOOST_ROOT="$(pwd)/boost_root"
          mkdir build
          cmake -G Ninja -S ./ -B ./build
      - name: CMake build
        run: cmake --build ./build
      - name: Build & Run tests
        run: |
          cmake --build ./build --target SMCE_Tests
          (cd build/test/; ctest --output-on-failure)

  build-macos:
    name: libSMCE - macOS (${{ matrix.compiler.name }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: GCC 10
            c: gcc-10
            cxx: g++-10
          - name: Clang/LLVM 11
            c: clang-11
            cxx: clang++-11
          - name: AppleClang 12
            c: clang
            cxx: clang++
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Check deps
        run: |
          brew install ninja arduino-cli
          ninja --version # technically not a dependency, but used to speedup builds
          cmake --version
          arduino-cli version
          arduino-cli core install arduino:avr
      - name: Cache Boost with GCC
        if: startsWith(matrix.compiler.name, 'GCC')
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/lib/cmake/Boost
            /usr/local/lib/cmake/boost_*
            /usr/local/Cellar/boost
          key: ${{ runner.os }}-boost-gcc
      - name: Install Boost with GCC
        if: startsWith(matrix.compiler.name, 'GCC')
        run: |
          sed -e 's/bootstrap_args = %W\[/bootstrap_args = %W\[\
          --with-toolset=gcc/' -i '' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
          brew install boost -s --cc=${{ matrix.compiler.c }}
          brew link boost
      - name: Install Boost with Clang
        if: (!startsWith(matrix.compiler.name, 'GCC'))
        run: brew install boost
      - name: CMake configure
        run: |
          [ "$CC" = "clang-11" ] && export CC="$(brew --prefix llvm)/bin/clang -stdlib=libc++ -nostdinc++ -I/usr/local/opt/llvm/include/c++/v1 -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          [ "$CXX" = "clang++-11" ] && export CXX="$(brew --prefix llvm)/bin/clang++ -stdlib=libc++ -nostdinc++ -I/usr/local/opt/llvm/include/c++/v1 -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          mkdir build
          cmake -G Ninja -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -S ./ -B ./build
      - name: CMake build
        run: cmake --build ./build
      - name: Build & Run tests
        run: |
          [ "$CC" = "clang-11" ] && export CC="$(brew --prefix llvm)/bin/clang -stdlib=libc++ -nostdinc++ -I/usr/local/opt/llvm/include/c++/v1 -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          [ "$CXX" = "clang++-11" ] && export CXX="$(brew --prefix llvm)/bin/clang++ -stdlib=libc++ -nostdinc++ -I/usr/local/opt/llvm/include/c++/v1 -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          cmake --build ./build --target SMCE_Tests
          (cd build/test/; ctest --output-on-failure)

  build-windows:
    name: libSMCE - Windows (${{ matrix.compiler.name }} & Boost ${{ matrix.boost.version }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: MSVC
            c: cl
            cxx: cl
#         - name: Clang/LLVM
#           c: clang-cl
#           cxx: clang++-cl
        boost:
          - version: 1.74.0
            slug: 1_74_0
          - version: 1.75.0
            slug: 1_75_0
#   env:
#     CC: ${{ matrix.compiler.c }}
#     CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir C:\local
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: C:\local\boost_${{ matrix.boost.slug }}
          key: ${{ runner.os }}-boost-${{ matrix.boost.version }}-64bit
      - if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: powershell
        run: .\ci\install-boost.ps1 '14.2' '${{ matrix.boost.version }}' '${{ matrix.boost.slug }}'
      - name: Check deps
        shell: bash
        run: |
          choco install ninja arduino-cli openssl > silence
          ninja --version
          arduino-cli version
          arduino-cli core install arduino:avr
      - uses: ilammy/msvc-dev-cmd@v1
      - name: CMake configure
        run: |
          mkdir build
          cmake -G Ninja -DBOOST_ROOT=C:\local\boost_${{ matrix.boost.slug }} -S ./ -B ./build
      - name: CMake build
        run: cmake --build ./build
      - name: Build & Run tests
        run: |
          cmake --build ./build --target SMCE_Tests
          cd build/test
          ctest --output-on-failure
  build-arch:
    name: libSMCE - ArchLinux (${{ matrix.compiler.name }})
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: GCC
            c: gcc
            cxx: g++
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - run: cd ~
      - uses: actions/checkout@v2
      - name: Check deps
        run: |
          pacman -Syu --noconfirm git cmake boost openssl arduino-cli ninja
          ninja --version
          arduino-cli version
          arduino-cli core install arduino:avr
      - name: CMake configure
        run: |
          mkdir build
          cmake -G Ninja -S ./ -B ./build
      - name: CMake build
        run: cmake --build ./build
      - name: Build & Run tests
        run: |
          cmake --build ./build --target SMCE_Tests
          cd build/test
          ctest --output-on-failure
